[package]
name = "script_bindings"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

# https://github.com/rust-lang/cargo/issues/3544
links = "script_bindings_crate"

[dependencies]
bitflags = { workspace = true }
deny_public_fields = { workspace = true }
dom_struct = { workspace = true }
domobject_derive = { workspace = true }
indexmap = { workspace = true }
js = { package = "spidermonkey-rs", path = "../spidermonkey-rs" }
jstraceable_derive = { path = "../jstraceable_derive" }
libc = { workspace = true }
log = { workspace = true }
malloc_size_of = { workspace = true }
malloc_size_of_derive = { workspace = true }
num-traits = { workspace = true }
parking_lot = { workspace = true }
phf = { workspace = true }
servo_arc = { workspace = true }
servo_config = { workspace = true }
servo_url = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true, optional = true }

[build-dependencies]
phf_codegen = "0.11"
phf_shared = "0.11"
serde_json = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(crown)'] }
unsafe_op_in_unsafe_fn = { level = "allow" }
