#[allow(unused_imports)]
mod raw {
  pub use crate::raw::*;
  pub use crate::raw::JS::*;
  pub use crate::raw::JS::dbg::*;
  pub use crate::raw::JS::detail::*;
  pub use crate::raw::js::*;
  pub use crate::raw::jsglue::*;
  pub use crate::raw::jsglue::NewProxyObject;
}
use crate::gc::*;
use jsapi_rs::jsapi::JS::{HandleObjectVector, HandleValueArray, MutableHandleIdVector};

wrap!(raw: pub fn ToBooleanSlow(v: HandleValue) -> bool);
wrap!(raw: pub fn ToNumberSlow(cx: *mut raw::JSContext, v: HandleValue, dp: *mut f64) -> bool);
wrap!(raw: pub fn ToInt8Slow(cx: *mut raw::JSContext, v: HandleValue, out: *mut i8) -> bool);
wrap!(raw: pub fn ToUint8Slow(cx: *mut raw::JSContext, v: HandleValue, out: *mut u8) -> bool);
wrap!(raw: pub fn ToInt16Slow(cx: *mut raw::JSContext, v: HandleValue, out: *mut i16) -> bool);
wrap!(raw: pub fn ToInt32Slow(cx: *mut raw::JSContext, v: HandleValue, out: *mut i32) -> bool);
wrap!(raw: pub fn ToUint32Slow(cx: *mut raw::JSContext, v: HandleValue, out: *mut u32) -> bool);
wrap!(raw: pub fn ToUint16Slow(cx: *mut raw::JSContext, v: HandleValue, out: *mut u16) -> bool);
wrap!(raw: pub fn ToInt64Slow(cx: *mut raw::JSContext, v: HandleValue, out: *mut i64) -> bool);
wrap!(raw: pub fn ToUint64Slow(cx: *mut raw::JSContext, v: HandleValue, out: *mut u64) -> bool);
wrap!(raw: pub fn ToStringSlow(cx: *mut raw::JSContext, v: HandleValue) -> *mut raw::JSString);
wrap!(raw: pub fn ToObjectSlow(cx: *mut raw::JSContext, v: HandleValue, reportScanStack: bool) -> *mut raw::JSObject);
wrap!(raw: pub fn NukeNonCCWProxy(cx: *mut raw::JSContext, proxy: HandleObject));
wrap!(raw: pub fn GetFirstSubsumedSavedFrame(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, selfHosted: raw::JS::SavedFrameSelfHosted) -> *mut raw::JSObject);
wrap!(raw: pub fn TransparentObjectWrapper(cx: *mut raw::JSContext, existing: HandleObject, obj: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn UnwrapOneCheckedDynamic(obj: HandleObject, cx: *mut raw::JSContext, stopAtWindowProxy: bool) -> *mut raw::JSObject);
wrap!(raw: pub fn RemapDeadWrapper(cx: *mut raw::JSContext, wobj: HandleObject, newTarget: HandleObject));
wrap!(raw: pub fn RemapAllWrappersForObject(cx: *mut raw::JSContext, oldTarget: HandleObject, newTarget: HandleObject) -> bool);
wrap!(raw: pub fn SetWindowProxy(cx: *mut raw::JSContext, global: HandleObject, windowProxy: HandleObject));
wrap!(raw: pub fn IsArgumentsObject(obj: HandleObject) -> bool);
wrap!(raw: pub fn EnqueueJob(cx: *mut raw::JSContext, job: HandleObject) -> bool);
wrap!(raw: pub fn AssertSameCompartment1(cx: *mut raw::JSContext, v: HandleValue));
wrap!(raw: pub fn NewFunctionByIdWithReservedAndProto(cx: *mut raw::JSContext, native: raw::JSNative, proto: HandleObject, nargs: ::std::os::raw::c_uint, flags: ::std::os::raw::c_uint, id: raw::jsid) -> *mut raw::JSFunction);
wrap!(raw: pub fn GetObjectProto(cx: *mut raw::JSContext, obj: HandleObject, proto: MutableHandleObject) -> bool);
wrap!(raw: pub fn GetRealmOriginalEval(cx: *mut raw::JSContext, eval: MutableHandleObject) -> bool);
wrap!(raw: pub fn GetPropertyKeys(cx: *mut raw::JSContext, obj: HandleObject, flags: ::std::os::raw::c_uint, props: MutableHandleIdVector) -> bool);
wrap!(raw: pub fn DateIsValid(cx: *mut raw::JSContext, obj: HandleObject, isValid: *mut bool) -> bool);
wrap!(raw: pub fn DateGetMsecSinceEpoch(cx: *mut raw::JSContext, obj: HandleObject, msecSinceEpoch: *mut f64) -> bool);
wrap!(raw: pub fn PrepareScriptEnvironmentAndInvoke(cx: *mut raw::JSContext, global: HandleObject, closure: *mut raw::js::ScriptEnvironmentPreparer_Closure));
wrap!(raw: pub fn GetElementsWithAdder(cx: *mut raw::JSContext, obj: HandleObject, receiver: HandleObject, begin: u32, end: u32, adder: *mut raw::js::ElementAdder) -> bool);
wrap!(raw: pub fn ExecuteInFrameScriptEnvironment(cx: *mut raw::JSContext, obj: HandleObject, script: HandleScript, scope: MutableHandleObject) -> bool);
wrap!(raw: pub fn ReportIsNotFunction(cx: *mut raw::JSContext, v: HandleValue) -> bool);
wrap!(raw: pub fn RemapRemoteWindowProxies(cx: *mut raw::JSContext, callback: *mut raw::js::CompartmentTransplantCallback, newTarget: MutableHandleObject));
wrap!(raw: pub fn AssertArgumentsAreSane(cx: *mut raw::JSContext, v: HandleValue));
wrap!(raw: pub fn ComputeThis(cx: *mut raw::JSContext, vp: *mut raw::JS::Value, thisObject: MutableHandleObject) -> bool);
wrap!(raw: pub fn CopyArrayBuffer(cx: *mut raw::JSContext, maybeArrayBuffer: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn DetachArrayBuffer(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn HasDefinedArrayBufferDetachKey(cx: *mut raw::JSContext, obj: HandleObject, isDefined: *mut bool) -> bool);
wrap!(raw: pub fn StealArrayBufferContents(cx: *mut raw::JSContext, obj: HandleObject) -> *mut ::std::os::raw::c_void);
wrap!(raw: pub fn ArrayBufferCopyData(cx: *mut raw::JSContext, toBlock: HandleObject, toIndex: usize, fromBlock: HandleObject, fromIndex: usize, count: usize) -> bool);
wrap!(raw: pub fn ArrayBufferClone(cx: *mut raw::JSContext, srcBuffer: HandleObject, srcByteOffset: usize, srcLength: usize) -> *mut raw::JSObject);
wrap!(raw: pub fn ToBigInt(cx: *mut raw::JSContext, val: HandleValue) -> *mut raw::JS::BigInt);
wrap!(raw: pub fn BigIntToString(cx: *mut raw::JSContext, bi: Handle<*mut raw::JS::BigInt>, radix: u8) -> *mut raw::JSString);
wrap!(raw: pub fn MaybeFreezeCtorAndPrototype(cx: *mut raw::JSContext, ctor: HandleObject, maybeProto: HandleObject) -> bool);
wrap!(raw: pub fn GetFunctionRealm(cx: *mut raw::JSContext, objArg: HandleObject) -> *mut raw::JS::Realm);
wrap!(raw: pub fn Evaluate(cx: *mut raw::JSContext, options: *const raw::JS::ReadOnlyCompileOptions, srcBuf: *mut raw::JS::SourceText<u16>, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn Evaluate1(cx: *mut raw::JSContext, envChain: *const raw::JS::EnvironmentChain, options: *const raw::JS::ReadOnlyCompileOptions, srcBuf: *mut raw::JS::SourceText<u16>, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn Evaluate2(cx: *mut raw::JSContext, options: *const raw::JS::ReadOnlyCompileOptions, srcBuf: *mut raw::JS::SourceText<raw::mozilla::Utf8Unit>, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn EvaluateUtf8Path(cx: *mut raw::JSContext, options: *const raw::JS::ReadOnlyCompileOptions, filename: *const ::std::os::raw::c_char, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn ExposeScriptToDebugger(cx: *mut raw::JSContext, script: HandleScript));
wrap!(raw: pub fn UpdateDebugMetadata(cx: *mut raw::JSContext, script: HandleScript, options: *const raw::JS::InstantiateOptions, privateValue: HandleValue, elementAttributeName: HandleString, introScript: HandleScript, scriptOrModule: HandleScript) -> bool);
wrap!(raw: pub fn OrdinaryToPrimitive(cx: *mut raw::JSContext, obj: HandleObject, type_: raw::JSType, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn ToGetterId(cx: *mut raw::JSContext, id: Handle<raw::JS::PropertyKey>, getterId: MutableHandle<raw::JS::PropertyKey>) -> bool);
wrap!(raw: pub fn ToSetterId(cx: *mut raw::JSContext, id: Handle<raw::JS::PropertyKey>, setterId: MutableHandle<raw::JS::PropertyKey>) -> bool);
wrap!(raw: pub fn ObjectIsDate(cx: *mut raw::JSContext, obj: HandleObject, isDate: *mut bool) -> bool);
wrap!(raw: pub fn StrictlyEqual(cx: *mut raw::JSContext, v1: HandleValue, v2: HandleValue, equal: *mut bool) -> bool);
wrap!(raw: pub fn LooselyEqual(cx: *mut raw::JSContext, v1: HandleValue, v2: HandleValue, equal: *mut bool) -> bool);
wrap!(raw: pub fn SameValue(cx: *mut raw::JSContext, v1: HandleValue, v2: HandleValue, same: *mut bool) -> bool);
wrap!(raw: pub fn ToJSONMaybeSafely(cx: *mut raw::JSContext, input: HandleObject, callback: raw::JSONWriteCallback, data: *mut ::std::os::raw::c_void) -> bool);
wrap!(raw: pub fn ToJSON(cx: *mut raw::JSContext, value: HandleValue, replacer: HandleObject, space: HandleValue, callback: raw::JSONWriteCallback, data: *mut ::std::os::raw::c_void) -> bool);
wrap!(raw: pub fn ParseJSONWithHandler(chars: *const raw::JS::Latin1Char, len: u32, handler: *mut raw::JS::JSONParseHandler) -> bool);
wrap!(raw: pub fn ParseJSONWithHandler1(chars: *const u16, len: u32, handler: *mut raw::JS::JSONParseHandler) -> bool);
wrap!(raw: pub fn AddSizeOfTab(cx: *mut raw::JSContext, obj: HandleObject, mallocSizeOf: raw::mozilla::MallocSizeOf, opv: *mut raw::JS::ObjectPrivateVisitor, sizes: *mut raw::JS::TabSizes) -> bool);
wrap!(raw: pub fn FinishDynamicModuleImport(cx: *mut raw::JSContext, evaluationPromise: HandleObject, referencingPrivate: HandleValue, moduleRequest: HandleObject, promise: HandleObject) -> bool);
wrap!(raw: pub fn ModuleLink(cx: *mut raw::JSContext, moduleRecord: HandleObject) -> bool);
wrap!(raw: pub fn ModuleEvaluate(cx: *mut raw::JSContext, moduleRecord: HandleObject, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn ThrowOnModuleEvaluationFailure(cx: *mut raw::JSContext, evaluationPromise: HandleObject, errorBehaviour: raw::JS::ModuleErrorBehaviour) -> bool);
wrap!(raw: pub fn GetRequestedModulesCount(cx: *mut raw::JSContext, moduleRecord: HandleObject) -> u32);
wrap!(raw: pub fn GetRequestedModuleSpecifier(cx: *mut raw::JSContext, moduleRecord: HandleObject, index: u32) -> *mut raw::JSString);
wrap!(raw: pub fn GetRequestedModuleSourcePos(cx: *mut raw::JSContext, moduleRecord: HandleObject, index: u32, lineNumber: *mut u32, columnNumber: *mut raw::JS::ColumnNumberOneOrigin));
wrap!(raw: pub fn GetRequestedModuleType(cx: *mut raw::JSContext, moduleRecord: HandleObject, index: u32) -> raw::JS::ModuleType);
wrap!(raw: pub fn GetModuleScript(moduleRecord: HandleObject) -> *mut raw::JSScript);
wrap!(raw: pub fn CreateModuleRequest(cx: *mut raw::JSContext, specifierArg: HandleString, moduleType: raw::JS::ModuleType) -> *mut raw::JSObject);
wrap!(raw: pub fn GetModuleRequestSpecifier(cx: *mut raw::JSContext, moduleRequestArg: HandleObject) -> *mut raw::JSString);
wrap!(raw: pub fn GetModuleRequestType(cx: *mut raw::JSContext, moduleRequestArg: HandleObject) -> raw::JS::ModuleType);
wrap!(raw: pub fn GetModuleObject(moduleScript: HandleScript) -> *mut raw::JSObject);
wrap!(raw: pub fn GetModuleNamespace(cx: *mut raw::JSContext, moduleRecord: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn GetModuleForNamespace(cx: *mut raw::JSContext, moduleNamespace: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn GetModuleEnvironment(cx: *mut raw::JSContext, moduleObj: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn GetBuiltinClass(cx: *mut raw::JSContext, obj: HandleObject, cls: *mut raw::js::ESClass) -> bool);
wrap!(raw: pub fn NewPromiseObject(cx: *mut raw::JSContext, executor: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn IsPromiseObject(obj: HandleObject) -> bool);
wrap!(raw: pub fn GetPromiseState(promise: HandleObject) -> raw::JS::PromiseState);
wrap!(raw: pub fn GetPromiseID(promise: HandleObject) -> u64);
wrap!(raw: pub fn GetPromiseIsHandled(promise: HandleObject) -> bool);
wrap!(raw: pub fn SetSettledPromiseIsHandled(cx: *mut raw::JSContext, promise: HandleObject) -> bool);
wrap!(raw: pub fn SetAnyPromiseIsHandled(cx: *mut raw::JSContext, promise: HandleObject) -> bool);
wrap!(raw: pub fn GetPromiseAllocationSite(promise: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn GetPromiseResolutionSite(promise: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn DumpPromiseAllocationSite(cx: *mut raw::JSContext, promise: HandleObject));
wrap!(raw: pub fn DumpPromiseResolutionSite(cx: *mut raw::JSContext, promise: HandleObject));
wrap!(raw: pub fn CallOriginalPromiseResolve(cx: *mut raw::JSContext, resolutionValue: HandleValue) -> *mut raw::JSObject);
wrap!(raw: pub fn CallOriginalPromiseReject(cx: *mut raw::JSContext, rejectionValue: HandleValue) -> *mut raw::JSObject);
wrap!(raw: pub fn ResolvePromise(cx: *mut raw::JSContext, promiseObj: HandleObject, resolutionValue: HandleValue) -> bool);
wrap!(raw: pub fn RejectPromise(cx: *mut raw::JSContext, promiseObj: HandleObject, rejectionValue: HandleValue) -> bool);
wrap!(raw: pub fn CallOriginalPromiseThen(cx: *mut raw::JSContext, promise: HandleObject, onFulfilled: HandleObject, onRejected: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn AddPromiseReactions(cx: *mut raw::JSContext, promise: HandleObject, onFulfilled: HandleObject, onRejected: HandleObject) -> bool);
wrap!(raw: pub fn AddPromiseReactionsIgnoringUnhandledRejection(cx: *mut raw::JSContext, promise: HandleObject, onFulfilled: HandleObject, onRejected: HandleObject) -> bool);
wrap!(raw: pub fn GetPromiseUserInputEventHandlingState(promise: HandleObject) -> raw::JS::PromiseUserInputEventHandlingState);
wrap!(raw: pub fn SetPromiseUserInputEventHandlingState(promise: HandleObject, state: raw::JS::PromiseUserInputEventHandlingState) -> bool);
wrap!(raw: pub fn GetWaitForAllPromise(cx: *mut raw::JSContext, promises: HandleObjectVector) -> *mut raw::JSObject);
wrap!(raw: pub fn ToCompletePropertyDescriptor(cx: *mut raw::JSContext, descriptor: HandleValue, desc: MutableHandle<raw::JS::PropertyDescriptor>) -> bool);
wrap!(raw: pub fn NewSymbol(cx: *mut raw::JSContext, description: HandleString) -> *mut raw::JS::Symbol);
wrap!(raw: pub fn GetSymbolFor(cx: *mut raw::JSContext, key: HandleString) -> *mut raw::JS::Symbol);
wrap!(raw: pub fn GetSymbolDescription(symbol: Handle<*mut raw::JS::Symbol>) -> *mut raw::JSString);
wrap!(raw: pub fn GetSymbolCode(symbol: Handle<*mut raw::JS::Symbol>) -> raw::JS::SymbolCode);
wrap!(raw: pub fn NewArrayObject(cx: *mut raw::JSContext, contents: *const HandleValueArray) -> *mut raw::JSObject);
wrap!(raw: pub fn IsArrayObject(cx: *mut raw::JSContext, value: HandleValue, isArray: *mut bool) -> bool);
wrap!(raw: pub fn IsArrayObject1(cx: *mut raw::JSContext, obj: HandleObject, isArray: *mut bool) -> bool);
wrap!(raw: pub fn GetArrayLength(cx: *mut raw::JSContext, obj: HandleObject, lengthp: *mut u32) -> bool);
wrap!(raw: pub fn SetArrayLength(cx: *mut raw::JSContext, obj: HandleObject, length: u32) -> bool);
wrap!(raw: pub fn IsArray(cx: *mut raw::JSContext, obj: HandleObject, isArray: *mut bool) -> bool);
wrap!(raw: pub fn IsArray1(cx: *mut raw::JSContext, obj: HandleObject, answer: *mut raw::JS::IsArrayAnswer) -> bool);
wrap!(raw: pub fn SetRegExpInput(cx: *mut raw::JSContext, obj: HandleObject, input: HandleString) -> bool);
wrap!(raw: pub fn ClearRegExpStatics(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn ExecuteRegExp(cx: *mut raw::JSContext, obj: HandleObject, reobj: HandleObject, chars: *const u16, length: usize, indexp: *mut usize, test: bool, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn ExecuteRegExpNoStatics(cx: *mut raw::JSContext, reobj: HandleObject, chars: *const u16, length: usize, indexp: *mut usize, test: bool, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn ObjectIsRegExp(cx: *mut raw::JSContext, obj: HandleObject, isRegExp: *mut bool) -> bool);
wrap!(raw: pub fn GetRegExpSource(cx: *mut raw::JSContext, obj: HandleObject) -> *mut raw::JSString);
wrap!(raw: pub fn CheckRegExpSyntax(cx: *mut raw::JSContext, chars: *const u16, length: usize, flags: raw::JS::RegExpFlags, error: MutableHandleValue) -> bool);
wrap!(raw: pub fn GetSavedFrameSource(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, sourcep: MutableHandleString, selfHosted: raw::JS::SavedFrameSelfHosted) -> raw::JS::SavedFrameResult);
wrap!(raw: pub fn GetSavedFrameSourceId(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, sourceIdp: *mut u32, selfHosted: raw::JS::SavedFrameSelfHosted) -> raw::JS::SavedFrameResult);
wrap!(raw: pub fn GetSavedFrameLine(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, linep: *mut u32, selfHosted: raw::JS::SavedFrameSelfHosted) -> raw::JS::SavedFrameResult);
wrap!(raw: pub fn GetSavedFrameColumn(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, columnp: *mut raw::JS::TaggedColumnNumberOneOrigin, selfHosted: raw::JS::SavedFrameSelfHosted) -> raw::JS::SavedFrameResult);
wrap!(raw: pub fn GetSavedFrameFunctionDisplayName(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, namep: MutableHandleString, selfHosted: raw::JS::SavedFrameSelfHosted) -> raw::JS::SavedFrameResult);
wrap!(raw: pub fn GetSavedFrameAsyncCause(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, asyncCausep: MutableHandleString, selfHosted: raw::JS::SavedFrameSelfHosted) -> raw::JS::SavedFrameResult);
wrap!(raw: pub fn GetSavedFrameAsyncParent(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, asyncParentp: MutableHandleObject, selfHosted: raw::JS::SavedFrameSelfHosted) -> raw::JS::SavedFrameResult);
wrap!(raw: pub fn GetSavedFrameParent(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, savedFrame: HandleObject, parentp: MutableHandleObject, selfHosted: raw::JS::SavedFrameSelfHosted) -> raw::JS::SavedFrameResult);
wrap!(raw: pub fn ConvertSavedFrameToPlainObject(cx: *mut raw::JSContext, savedFrame: HandleObject, selfHosted: raw::JS::SavedFrameSelfHosted) -> *mut raw::JSObject);
wrap!(raw: pub fn NewReadableDefaultStreamObject(cx: *mut raw::JSContext, underlyingSource: HandleObject, size: HandleFunction, highWaterMark: f64, proto: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn NewReadableExternalSourceStreamObject(cx: *mut raw::JSContext, underlyingSource: *mut raw::JS::ReadableStreamUnderlyingSource, nsISupportsObject_alreadyAddreffed: *mut ::std::os::raw::c_void, proto: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn ReadableStreamGetExternalUnderlyingSource(cx: *mut raw::JSContext, stream: HandleObject, source: *mut *mut raw::JS::ReadableStreamUnderlyingSource) -> bool);
wrap!(raw: pub fn ReadableStreamReleaseExternalUnderlyingSource(cx: *mut raw::JSContext, stream: HandleObject) -> bool);
wrap!(raw: pub fn ReadableStreamUpdateDataAvailableFromSource(cx: *mut raw::JSContext, stream: HandleObject, availableData: u32) -> bool);
wrap!(raw: pub fn ReadableStreamGetMode(cx: *mut raw::JSContext, stream: HandleObject, mode: *mut raw::JS::ReadableStreamMode) -> bool);
wrap!(raw: pub fn ReadableStreamGetStoredError(cx: *mut raw::JSContext, stream: HandleObject) -> raw::JS::Value);
wrap!(raw: pub fn ReadableStreamIsReadable(cx: *mut raw::JSContext, stream: HandleObject, result: *mut bool) -> bool);
wrap!(raw: pub fn ReadableStreamIsLocked(cx: *mut raw::JSContext, stream: HandleObject, result: *mut bool) -> bool);
wrap!(raw: pub fn ReadableStreamIsDisturbed(cx: *mut raw::JSContext, stream: HandleObject, result: *mut bool) -> bool);
wrap!(raw: pub fn ReadableStreamIsErrored(cx: *mut raw::JSContext, stream: HandleObject, result: *mut bool) -> bool);
wrap!(raw: pub fn ReadableStreamCancel(cx: *mut raw::JSContext, stream: HandleObject, reason: HandleValue) -> *mut raw::JSObject);
wrap!(raw: pub fn ReadableStreamGetReader(cx: *mut raw::JSContext, stream: HandleObject, mode: raw::JS::ReadableStreamReaderMode) -> *mut raw::JSObject);
wrap!(raw: pub fn ReadableStreamGetController(cx: *mut raw::JSContext, stream: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn ReadableStreamControllerGetUnderlyingSource(cx: *mut raw::JSContext, controller: HandleObject, source: MutableHandleValue) -> bool);
wrap!(raw: pub fn CheckReadableStreamControllerCanCloseOrEnqueue(cx: *mut raw::JSContext, controller: HandleObject, action: *const ::std::os::raw::c_char) -> bool);
wrap!(raw: pub fn ReadableStreamControllerShouldCallPull(cx: *mut raw::JSContext, controller: HandleObject) -> bool);
wrap!(raw: pub fn ReadableStreamTee(cx: *mut raw::JSContext, stream: HandleObject, branch1Stream: MutableHandleObject, branch2Stream: MutableHandleObject) -> bool);
wrap!(raw: pub fn ReadableStreamClose(cx: *mut raw::JSContext, stream: HandleObject) -> bool);
wrap!(raw: pub fn ReadableStreamReaderIsClosed(cx: *mut raw::JSContext, reader: HandleObject, result: *mut bool) -> bool);
wrap!(raw: pub fn ReadableStreamEnqueue(cx: *mut raw::JSContext, stream: HandleObject, chunk: HandleValue) -> bool);
wrap!(raw: pub fn ReadableStreamError(cx: *mut raw::JSContext, stream: HandleObject, error: HandleValue) -> bool);
wrap!(raw: pub fn ReadableStreamReaderCancel(cx: *mut raw::JSContext, reader: HandleObject, reason: HandleValue) -> bool);
wrap!(raw: pub fn ReadableStreamReaderReleaseLock(cx: *mut raw::JSContext, reader: HandleObject) -> bool);
wrap!(raw: pub fn ReadableStreamBYOBReaderRead(cx: *mut raw::JSContext, reader: HandleObject, view: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn ReadableStreamDefaultReaderRead(cx: *mut raw::JSContext, reader: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn NewWritableDefaultStreamObject(cx: *mut raw::JSContext, underlyingSink: HandleObject, size: HandleFunction, highWaterMark: f64, proto: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn WritableStreamGetState(cx: *mut raw::JSContext, stream: HandleObject) -> raw::JS::WritableStreamState);
wrap!(raw: pub fn WritableStreamIsLocked(cx: *mut raw::JSContext, stream: HandleObject) -> bool);
wrap!(raw: pub fn WritableStreamGetWriter(cx: *mut raw::JSContext, stream: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn WritableStreamGetController(cx: *mut raw::JSContext, stream: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn WritableStreamControllerGetUnderlyingSink(cx: *mut raw::JSContext, controller: HandleObject) -> raw::JS::Value);
wrap!(raw: pub fn WritableStreamError(cx: *mut raw::JSContext, stream: HandleObject, error: HandleValue) -> bool);
wrap!(raw: pub fn WritableStreamGetStoredError(cx: *mut raw::JSContext, stream: HandleObject) -> raw::JS::Value);
wrap!(raw: pub fn IsWasmModuleObject(obj: HandleObject) -> bool);
wrap!(raw: pub fn GetWasmModule(obj: HandleObject) -> raw::RefPtr<raw::JS::WasmModule>);
wrap!(raw: pub fn Call(cx: *mut raw::JSContext, thisv: HandleValue, fun: HandleValue, args: *const HandleValueArray, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn Construct(cx: *mut raw::JSContext, fun: HandleValue, newTarget: HandleObject, args: *const HandleValueArray, objp: MutableHandleObject) -> bool);
wrap!(raw: pub fn Construct1(cx: *mut raw::JSContext, fun: HandleValue, args: *const HandleValueArray, objp: MutableHandleObject) -> bool);
wrap!(raw: pub fn ExceptionStackOrNull(obj: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn MapSize(cx: *mut raw::JSContext, obj: HandleObject) -> u32);
wrap!(raw: pub fn MapGet(cx: *mut raw::JSContext, obj: HandleObject, key: HandleValue, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn MapHas(cx: *mut raw::JSContext, obj: HandleObject, key: HandleValue, rval: *mut bool) -> bool);
wrap!(raw: pub fn MapSet(cx: *mut raw::JSContext, obj: HandleObject, key: HandleValue, val: HandleValue) -> bool);
wrap!(raw: pub fn MapDelete(cx: *mut raw::JSContext, obj: HandleObject, key: HandleValue, rval: *mut bool) -> bool);
wrap!(raw: pub fn MapClear(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn MapKeys(cx: *mut raw::JSContext, obj: HandleObject, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn MapValues(cx: *mut raw::JSContext, obj: HandleObject, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn MapEntries(cx: *mut raw::JSContext, obj: HandleObject, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn MapForEach(cx: *mut raw::JSContext, obj: HandleObject, callbackFn: HandleValue, thisVal: HandleValue) -> bool);
wrap!(raw: pub fn SetSize(cx: *mut raw::JSContext, obj: HandleObject) -> u32);
wrap!(raw: pub fn SetHas(cx: *mut raw::JSContext, obj: HandleObject, key: HandleValue, rval: *mut bool) -> bool);
wrap!(raw: pub fn SetDelete(cx: *mut raw::JSContext, obj: HandleObject, key: HandleValue, rval: *mut bool) -> bool);
wrap!(raw: pub fn SetAdd(cx: *mut raw::JSContext, obj: HandleObject, key: HandleValue) -> bool);
wrap!(raw: pub fn SetClear(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn SetKeys(cx: *mut raw::JSContext, obj: HandleObject, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn SetValues(cx: *mut raw::JSContext, obj: HandleObject, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn SetEntries(cx: *mut raw::JSContext, obj: HandleObject, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn SetForEach(cx: *mut raw::JSContext, obj: HandleObject, callbackFn: HandleValue, thisVal: HandleValue) -> bool);
wrap!(raw: pub fn CaptureCurrentStack(cx: *mut raw::JSContext, stackp: MutableHandleObject, capture: *mut raw::JS::StackCapture, startAfter: HandleObject) -> bool);
wrap!(raw: pub fn BuildStackString(cx: *mut raw::JSContext, principals: *mut raw::JSPrincipals, stack: HandleObject, stringp: MutableHandleString, indent: usize, stackFormat: raw::js::StackFormat) -> bool);
wrap!(raw: pub fn GetWeakMapEntry(cx: *mut raw::JSContext, mapObj: HandleObject, key: HandleValue, val: MutableHandleValue) -> bool);
wrap!(raw: pub fn SetWeakMapEntry(cx: *mut raw::JSContext, mapObj: HandleObject, key: HandleValue, val: HandleValue) -> bool);
wrap!(raw: pub fn ProtoKeyToId(cx: *mut raw::JSContext, key: raw::JSProtoKey, idp: MutableHandleId));
wrap!(raw: pub fn ToPrimitive(cx: *mut raw::JSContext, obj: HandleObject, hint: raw::JSType, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn OrdinaryHasInstance(cx: *mut raw::JSContext, objArg: HandleObject, v: HandleValue, bp: *mut bool) -> bool);
wrap!(raw: pub fn IsMapObject(cx: *mut raw::JSContext, obj: HandleObject, isMap: *mut bool) -> bool);
wrap!(raw: pub fn IsSetObject(cx: *mut raw::JSContext, obj: HandleObject, isSet: *mut bool) -> bool);
wrap!(raw: pub fn GetSelfHostedFunction(cx: *mut raw::JSContext, selfHostedName: *const ::std::os::raw::c_char, id: HandleId, nargs: ::std::os::raw::c_uint) -> *mut raw::JSFunction);
wrap!(raw: pub fn NewFunctionFromSpec(cx: *mut raw::JSContext, fs: *const raw::JSFunctionSpec, id: HandleId) -> *mut raw::JSFunction);
wrap!(raw: pub fn PropertySpecNameEqualsId(name: raw::JSPropertySpec_Name, id: HandleId) -> bool);
wrap!(raw: pub fn ForceLexicalInitialization(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn DefineConstants(cx: *mut raw::JSContext, obj: HandleObject, cs: *const raw::jsglue::ConstantSpec) -> bool);
wrap!(raw: pub fn InitProperties(cx: *mut raw::JSContext, obj: HandleObject, properties: *const raw::jsglue::NativeProperties) -> bool);
wrap!(raw: pub fn DefineToStringTag(cx: *mut raw::JSContext, obj: HandleObject, class_name: HandleString) -> bool);
wrap!(raw: pub fn CreateBuiltinClass(cx: *mut raw::JSContext, jsCtor: raw::JSNative, argc: ::std::os::raw::c_uint, cls: *const raw::JSClass, properties: *const raw::jsglue::NativeProperties, ctorProperties: *const raw::jsglue::NativeProperties, protoClass: *const raw::JSClass, protoProto: HandleObject, global: HandleObject, defineOnGlobal: bool) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_ForOfIteratorInit(iterator: *mut raw::JS::ForOfIterator, iterable: HandleValue, nonIterableBehavior: raw::JS::ForOfIterator_NonIterableBehavior) -> bool);
wrap!(raw: pub fn JS_ForOfIteratorNext(iterator: *mut raw::JS::ForOfIterator, val: MutableHandleValue, done: *mut bool) -> bool);
wrap!(raw: pub fn FromPropertyDescriptor(cx: *mut raw::JSContext, desc_: Handle<raw::JS::PropertyDescriptor>, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_GetPropertyDescriptor(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, desc: MutableHandle<raw::JS::PropertyDescriptor>, holder: MutableHandleObject, isNone: *mut bool) -> bool);
wrap!(raw: pub fn JS_GetOwnPropertyDescriptorById(cx: *mut raw::JSContext, obj: HandleObject, id: HandleId, desc: MutableHandle<raw::JS::PropertyDescriptor>, isNone: *mut bool) -> bool);
wrap!(raw: pub fn JS_GetOwnPropertyDescriptor(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, desc: MutableHandle<raw::JS::PropertyDescriptor>, isNone: *mut bool) -> bool);
wrap!(raw: pub fn JS_GetOwnUCPropertyDescriptor(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, desc: MutableHandle<raw::JS::PropertyDescriptor>, isNone: *mut bool) -> bool);
wrap!(raw: pub fn JS_GetPropertyDescriptorById(cx: *mut raw::JSContext, obj: HandleObject, id: HandleId, desc: MutableHandle<raw::JS::PropertyDescriptor>, holder: MutableHandleObject, isNone: *mut bool) -> bool);
wrap!(raw: pub fn JS_GetUCPropertyDescriptor(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, desc: MutableHandle<raw::JS::PropertyDescriptor>, holder: MutableHandleObject, isNone: *mut bool) -> bool);
wrap!(raw: pub fn SetPropertyIgnoringNamedGetter(cx: *mut raw::JSContext, obj: HandleObject, id: HandleId, v: HandleValue, receiver: HandleValue, ownDesc: *const Handle<raw::JS::PropertyDescriptor>, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn CreateError(cx: *mut raw::JSContext, type_: raw::JSExnType, stack: HandleObject, fileName: HandleString, lineNumber: u32, columnNumber: u32, report: *mut raw::JSErrorReport, message: HandleString, cause: HandleValue, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn GetExceptionCause(exc: *mut raw::JSObject, dest: MutableHandleValue));
wrap!(raw: pub fn InvokeGetOwnPropertyDescriptor(handler: *const ::std::os::raw::c_void, cx: *mut raw::JSContext, proxy: HandleObject, id: HandleId, desc: MutableHandle<raw::JS::PropertyDescriptor>, isNone: *mut bool) -> bool);
wrap!(raw: pub fn InvokeHasOwn(handler: *const ::std::os::raw::c_void, cx: *mut raw::JSContext, proxy: HandleObject, id: HandleId, bp: *mut bool) -> bool);
wrap!(raw: pub fn CallJitGetterOp(info: *const raw::JSJitInfo, cx: *mut raw::JSContext, thisObj: HandleObject, specializedThis: *mut ::std::os::raw::c_void, argc: ::std::os::raw::c_uint, vp: *mut raw::JS::Value) -> bool);
wrap!(raw: pub fn CallJitSetterOp(info: *const raw::JSJitInfo, cx: *mut raw::JSContext, thisObj: HandleObject, specializedThis: *mut ::std::os::raw::c_void, argc: ::std::os::raw::c_uint, vp: *mut raw::JS::Value) -> bool);
wrap!(raw: pub fn CallJitMethodOp(info: *const raw::JSJitInfo, cx: *mut raw::JSContext, thisObj: HandleObject, specializedThis: *mut ::std::os::raw::c_void, argc: u32, vp: *mut raw::JS::Value) -> bool);
wrap!(raw: pub fn NewProxyObject(aCx: *mut raw::JSContext, aHandler: *const ::std::os::raw::c_void, aPriv: HandleValue, proto: *mut raw::JSObject, aClass: *const raw::JSClass, aLazyProto: bool) -> *mut raw::JSObject);
wrap!(raw: pub fn WrapperNew(aCx: *mut raw::JSContext, aObj: HandleObject, aHandler: *const ::std::os::raw::c_void, aClass: *const raw::JSClass) -> *mut raw::JSObject);
wrap!(raw: pub fn NewWindowProxy(aCx: *mut raw::JSContext, aObj: HandleObject, aHandler: *const ::std::os::raw::c_void) -> *mut raw::JSObject);
wrap!(raw: pub fn RUST_JSID_IS_INT(id: HandleId) -> bool);
wrap!(raw: pub fn int_to_jsid(i: i32, id: MutableHandleId));
wrap!(raw: pub fn RUST_JSID_TO_INT(id: HandleId) -> i32);
wrap!(raw: pub fn RUST_JSID_IS_STRING(id: HandleId) -> bool);
wrap!(raw: pub fn RUST_JSID_TO_STRING(id: HandleId) -> *mut raw::JSString);
wrap!(raw: pub fn RUST_SYMBOL_TO_JSID(sym: *mut raw::JS::Symbol, id: MutableHandleId));
wrap!(raw: pub fn RUST_JSID_IS_VOID(id: HandleId) -> bool);
wrap!(raw: pub fn RUST_INTERNED_STRING_TO_JSID(cx: *mut raw::JSContext, str_: *mut raw::JSString, id: MutableHandleId));
wrap!(raw: pub fn AppendToIdVector(v: MutableHandleIdVector, id: HandleId) -> bool);
wrap!(raw: pub fn JS_GetPromiseResult(promise: HandleObject, dest: MutableHandleValue));
wrap!(raw: pub fn JS_GetScriptPrivate(script: *mut raw::JSScript, dest: MutableHandleValue));
wrap!(raw: pub fn JS_MaybeGetScriptPrivate(obj: *mut raw::JSObject, dest: MutableHandleValue));
wrap!(raw: pub fn JS_GetModulePrivate(module: *mut raw::JSObject, dest: MutableHandleValue));
wrap!(raw: pub fn JS_GetScriptedCallerPrivate(cx: *mut raw::JSContext, dest: MutableHandleValue));
wrap!(raw: pub fn JS_GetRegExpFlags(cx: *mut raw::JSContext, obj: HandleObject, flags: *mut raw::JS::RegExpFlags));
wrap!(raw: pub fn EncodeStringToUTF8(cx: *mut raw::JSContext, str_: HandleString, cb: raw::jsglue::EncodedStringCallback));
wrap!(raw: pub fn SetDataPropertyDescriptor(desc: MutableHandle<raw::JS::PropertyDescriptor>, value: HandleValue, attrs: u32));
wrap!(raw: pub fn SetAccessorPropertyDescriptor(desc: MutableHandle<raw::JS::PropertyDescriptor>, getter: HandleObject, setter: HandleObject, attrs: u32));
wrap!(raw: pub fn JS_Utf8BufferIsCompilableUnit(cx: *mut raw::JSContext, obj: HandleObject, utf8: *const ::std::os::raw::c_char, length: usize) -> bool);
wrap!(raw: pub fn JS_ExecuteScript(cx: *mut raw::JSContext, script: HandleScript, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_ExecuteScript1(cx: *mut raw::JSContext, script: HandleScript) -> bool);
wrap!(raw: pub fn JS_ExecuteScript2(cx: *mut raw::JSContext, envChain: *const raw::JS::EnvironmentChain, script: HandleScript, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_ExecuteScript3(cx: *mut raw::JSContext, envChain: *const raw::JS::EnvironmentChain, script: HandleScript) -> bool);
wrap!(raw: pub fn JS_EncodeStringToUTF8(cx: *mut raw::JSContext, str_: HandleString) -> raw::JS::UniqueChars);
wrap!(raw: pub fn JS_Stringify(cx: *mut raw::JSContext, value: MutableHandleValue, replacer: HandleObject, space: HandleValue, callback: raw::JSONWriteCallback, data: *mut ::std::os::raw::c_void) -> bool);
wrap!(raw: pub fn JS_StringifyWithLengthHint(cx: *mut raw::JSContext, value: MutableHandleValue, replacer: HandleObject, space: HandleValue, callback: raw::JSONWriteCallback, data: *mut ::std::os::raw::c_void, lengthHint: usize) -> bool);
wrap!(raw: pub fn JS_ParseJSON(cx: *mut raw::JSContext, chars: *const u16, len: u32, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_ParseJSON1(cx: *mut raw::JSContext, str_: HandleString, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_ParseJSON2(cx: *mut raw::JSContext, chars: *const raw::JS::Latin1Char, len: u32, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_ParseJSONWithReviver(cx: *mut raw::JSContext, chars: *const u16, len: u32, reviver: HandleValue, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_ParseJSONWithReviver1(cx: *mut raw::JSContext, str_: HandleString, reviver: HandleValue, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_NewDependentString(cx: *mut raw::JSContext, str_: HandleString, start: usize, length: usize) -> *mut raw::JSString);
wrap!(raw: pub fn JS_ConcatStrings(cx: *mut raw::JSContext, left: HandleString, right: HandleString) -> *mut raw::JSString);
wrap!(raw: pub fn JS_ReadStructuredClone(cx: *mut raw::JSContext, data: *const raw::JSStructuredCloneData, version: u32, scope: raw::JS::StructuredCloneScope, vp: MutableHandleValue, cloneDataPolicy: *const raw::JS::CloneDataPolicy, optionalCallbacks: *const raw::JSStructuredCloneCallbacks, closure: *mut ::std::os::raw::c_void) -> bool);
wrap!(raw: pub fn JS_WriteStructuredClone(cx: *mut raw::JSContext, v: HandleValue, data: *mut raw::JSStructuredCloneData, scope: raw::JS::StructuredCloneScope, cloneDataPolicy: *const raw::JS::CloneDataPolicy, optionalCallbacks: *const raw::JSStructuredCloneCallbacks, closure: *mut ::std::os::raw::c_void, transferable: HandleValue) -> bool);
wrap!(raw: pub fn JS_StructuredClone(cx: *mut raw::JSContext, v: HandleValue, vp: MutableHandleValue, optionalCallbacks: *const raw::JSStructuredCloneCallbacks, closure: *mut ::std::os::raw::c_void) -> bool);
wrap!(raw: pub fn JS_ReadString(r: *mut raw::JSStructuredCloneReader, str_: MutableHandleString) -> bool);
wrap!(raw: pub fn JS_ReadTypedArray(r: *mut raw::JSStructuredCloneReader, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_WriteString(w: *mut raw::JSStructuredCloneWriter, str_: HandleString) -> bool);
wrap!(raw: pub fn JS_WriteTypedArray(w: *mut raw::JSStructuredCloneWriter, v: HandleValue) -> bool);
wrap!(raw: pub fn JS_ObjectNotWritten(w: *mut raw::JSStructuredCloneWriter, obj: HandleObject) -> bool);
wrap!(raw: pub fn JS_NewInt8ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewInt8ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewUint8ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewUint8ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewInt16ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewInt16ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewUint16ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewUint16ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewInt32ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewInt32ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewUint32ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewUint32ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewFloat32ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewFloat32ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewFloat64ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewFloat64ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewUint8ClampedArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewUint8ClampedArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewBigInt64ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewBigInt64ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewBigUint64ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewBigUint64ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewFloat16ArrayFromArray(cx: *mut raw::JSContext, array: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewFloat16ArrayWithBuffer(cx: *mut raw::JSContext, arrayBuffer: HandleObject, byteOffset: usize, length: i64) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_GetArrayBufferViewBuffer(cx: *mut raw::JSContext, obj: HandleObject, isSharedMemory: *mut bool) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewDataView(cx: *mut raw::JSContext, buffer: HandleObject, byteOffset: usize, byteLength: usize) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_CallFunctionValue(cx: *mut raw::JSContext, obj: HandleObject, fval: HandleValue, args: *const HandleValueArray, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_CallFunction(cx: *mut raw::JSContext, obj: HandleObject, fun: Handle<*mut raw::JSFunction>, args: *const HandleValueArray, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_CallFunctionName(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, args: *const HandleValueArray, rval: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_DefineDebuggerObject(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn JS_GetPendingException(cx: *mut raw::JSContext, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_SetPendingException(cx: *mut raw::JSContext, v: HandleValue, behavior: raw::JS::ExceptionStackBehavior));
wrap!(raw: pub fn JS_ErrorFromException(cx: *mut raw::JSContext, obj: HandleObject) -> *mut raw::JSErrorReport);
wrap!(raw: pub fn JS_FireOnNewGlobalObject(cx: *mut raw::JSContext, global: HandleObject));
wrap!(raw: pub fn JS_DefinePropertyById(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, desc: Handle<raw::JS::PropertyDescriptor>, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById1(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, desc: Handle<raw::JS::PropertyDescriptor>) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById2(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, value: HandleValue, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById3(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, getter: raw::JSNative, setter: raw::JSNative, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById4(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, getter: HandleObject, setter: HandleObject, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById5(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, value: HandleObject, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById6(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, value: HandleString, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById7(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, value: i32, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById8(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, value: u32, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefinePropertyById9(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, value: f64, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, value: HandleValue, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineProperty1(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, getter: raw::JSNative, setter: raw::JSNative, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineProperty2(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, getter: HandleObject, setter: HandleObject, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineProperty3(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, value: HandleObject, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineProperty4(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, value: HandleString, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineProperty5(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, value: i32, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineProperty6(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, value: u32, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineProperty7(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, value: f64, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, desc: Handle<raw::JS::PropertyDescriptor>, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty1(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, desc: Handle<raw::JS::PropertyDescriptor>) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty2(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, value: HandleValue, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty3(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, getter: HandleObject, setter: HandleObject, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty4(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, value: HandleObject, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty5(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, value: HandleString, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty6(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, value: i32, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty7(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, value: u32, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineUCProperty8(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, value: f64, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineElement(cx: *mut raw::JSContext, obj: HandleObject, index: u32, value: HandleValue, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineElement1(cx: *mut raw::JSContext, obj: HandleObject, index: u32, getter: HandleObject, setter: HandleObject, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineElement2(cx: *mut raw::JSContext, obj: HandleObject, index: u32, value: HandleObject, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineElement3(cx: *mut raw::JSContext, obj: HandleObject, index: u32, value: HandleString, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineElement4(cx: *mut raw::JSContext, obj: HandleObject, index: u32, value: i32, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineElement5(cx: *mut raw::JSContext, obj: HandleObject, index: u32, value: u32, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_DefineElement6(cx: *mut raw::JSContext, obj: HandleObject, index: u32, value: f64, attrs: ::std::os::raw::c_uint) -> bool);
wrap!(raw: pub fn JS_HasPropertyById(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_HasProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_HasUCProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, vp: *mut bool) -> bool);
wrap!(raw: pub fn JS_HasElement(cx: *mut raw::JSContext, obj: HandleObject, index: u32, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_HasOwnPropertyById(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_HasOwnProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_ForwardGetPropertyTo(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, receiver: HandleValue, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_ForwardGetElementTo(cx: *mut raw::JSContext, obj: HandleObject, index: u32, receiver: HandleObject, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_GetPropertyById(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_GetProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_GetUCProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_GetElement(cx: *mut raw::JSContext, obj: HandleObject, index: u32, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_ForwardSetPropertyTo(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, v: HandleValue, receiver: HandleValue, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn JS_SetPropertyById(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, v: HandleValue) -> bool);
wrap!(raw: pub fn JS_SetProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, v: HandleValue) -> bool);
wrap!(raw: pub fn JS_SetUCProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, v: HandleValue) -> bool);
wrap!(raw: pub fn JS_SetElement(cx: *mut raw::JSContext, obj: HandleObject, index: u32, v: HandleValue) -> bool);
wrap!(raw: pub fn JS_SetElement1(cx: *mut raw::JSContext, obj: HandleObject, index: u32, v: HandleObject) -> bool);
wrap!(raw: pub fn JS_SetElement2(cx: *mut raw::JSContext, obj: HandleObject, index: u32, v: HandleString) -> bool);
wrap!(raw: pub fn JS_SetElement3(cx: *mut raw::JSContext, obj: HandleObject, index: u32, v: i32) -> bool);
wrap!(raw: pub fn JS_SetElement4(cx: *mut raw::JSContext, obj: HandleObject, index: u32, v: u32) -> bool);
wrap!(raw: pub fn JS_SetElement5(cx: *mut raw::JSContext, obj: HandleObject, index: u32, v: f64) -> bool);
wrap!(raw: pub fn JS_DeletePropertyById(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn JS_DeleteProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn JS_DeleteUCProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn JS_DeleteElement(cx: *mut raw::JSContext, obj: HandleObject, index: u32, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn JS_DeletePropertyById1(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>) -> bool);
wrap!(raw: pub fn JS_DeleteProperty1(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char) -> bool);
wrap!(raw: pub fn JS_DeleteElement1(cx: *mut raw::JSContext, obj: HandleObject, index: u32) -> bool);
wrap!(raw: pub fn JS_Enumerate(cx: *mut raw::JSContext, obj: HandleObject, props: MutableHandle<raw::JS::IdVector>) -> bool);
wrap!(raw: pub fn JS_DefineObject(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, clasp: *const raw::JSClass, attrs: ::std::os::raw::c_uint) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_DefineProperties(cx: *mut raw::JSContext, obj: HandleObject, ps: *const raw::JSPropertySpec) -> bool);
wrap!(raw: pub fn JS_AlreadyHasOwnPropertyById(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_AlreadyHasOwnProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_AlreadyHasOwnUCProperty(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_AlreadyHasOwnElement(cx: *mut raw::JSContext, obj: HandleObject, index: u32, foundp: *mut bool) -> bool);
wrap!(raw: pub fn JS_DefineFunctions(cx: *mut raw::JSContext, obj: HandleObject, fs: *const raw::JSFunctionSpec) -> bool);
wrap!(raw: pub fn JS_DefineFunction(cx: *mut raw::JSContext, obj: HandleObject, name: *const ::std::os::raw::c_char, call: raw::JSNative, nargs: ::std::os::raw::c_uint, attrs: ::std::os::raw::c_uint) -> *mut raw::JSFunction);
wrap!(raw: pub fn JS_DefineUCFunction(cx: *mut raw::JSContext, obj: HandleObject, name: *const u16, namelen: usize, call: raw::JSNative, nargs: ::std::os::raw::c_uint, attrs: ::std::os::raw::c_uint) -> *mut raw::JSFunction);
wrap!(raw: pub fn JS_DefineFunctionById(cx: *mut raw::JSContext, obj: HandleObject, id: Handle<raw::jsid>, call: raw::JSNative, nargs: ::std::os::raw::c_uint, attrs: ::std::os::raw::c_uint) -> *mut raw::JSFunction);
wrap!(raw: pub fn JS_RefreshCrossCompartmentWrappers(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn JS_ValueToObject(cx: *mut raw::JSContext, v: HandleValue, objp: MutableHandleObject) -> bool);
wrap!(raw: pub fn JS_ValueToFunction(cx: *mut raw::JSContext, v: HandleValue) -> *mut raw::JSFunction);
wrap!(raw: pub fn JS_ValueToConstructor(cx: *mut raw::JSContext, v: HandleValue) -> *mut raw::JSFunction);
wrap!(raw: pub fn JS_ValueToSource(cx: *mut raw::JSContext, v: HandleValue) -> *mut raw::JSString);
wrap!(raw: pub fn JS_TypeOfValue(cx: *mut raw::JSContext, v: HandleValue) -> raw::JSType);
wrap!(raw: pub fn JS_WrapObject(cx: *mut raw::JSContext, objp: MutableHandleObject) -> bool);
wrap!(raw: pub fn JS_WrapValue(cx: *mut raw::JSContext, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_TransplantObject(cx: *mut raw::JSContext, origobj: HandleObject, target: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_ResolveStandardClass(cx: *mut raw::JSContext, obj: HandleObject, id: HandleId, resolved: *mut bool) -> bool);
wrap!(raw: pub fn JS_EnumerateStandardClasses(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn JS_NewEnumerateStandardClasses(cx: *mut raw::JSContext, obj: HandleObject, properties: MutableHandleIdVector, enumerableOnly: bool) -> bool);
wrap!(raw: pub fn JS_NewEnumerateStandardClassesIncludingResolved(cx: *mut raw::JSContext, obj: HandleObject, properties: MutableHandleIdVector, enumerableOnly: bool) -> bool);
wrap!(raw: pub fn JS_GetClassObject(cx: *mut raw::JSContext, key: raw::JSProtoKey, objp: MutableHandleObject) -> bool);
wrap!(raw: pub fn JS_GetClassPrototype(cx: *mut raw::JSContext, key: raw::JSProtoKey, objp: MutableHandleObject) -> bool);
wrap!(raw: pub fn JS_IdToProtoKey(cx: *mut raw::JSContext, id: HandleId) -> raw::JSProtoKey);
wrap!(raw: pub fn JS_InitReflectParse(cx: *mut raw::JSContext, global: HandleObject) -> bool);
wrap!(raw: pub fn JS_DefineProfilingFunctions(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn JS_ValueToId(cx: *mut raw::JSContext, v: HandleValue, idp: MutableHandleId) -> bool);
wrap!(raw: pub fn JS_StringToId(cx: *mut raw::JSContext, s: HandleString, idp: MutableHandleId) -> bool);
wrap!(raw: pub fn JS_IdToValue(cx: *mut raw::JSContext, id: raw::jsid, vp: MutableHandleValue) -> bool);
wrap!(raw: pub fn JS_InitClass(cx: *mut raw::JSContext, obj: HandleObject, protoClass: *const raw::JSClass, protoProto: HandleObject, name: *const ::std::os::raw::c_char, constructor: raw::JSNative, nargs: ::std::os::raw::c_uint, ps: *const raw::JSPropertySpec, fs: *const raw::JSFunctionSpec, static_ps: *const raw::JSPropertySpec, static_fs: *const raw::JSFunctionSpec) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_LinkConstructorAndPrototype(cx: *mut raw::JSContext, ctor: HandleObject, proto: HandleObject) -> bool);
wrap!(raw: pub fn JS_InstanceOf(cx: *mut raw::JSContext, obj: HandleObject, clasp: *const raw::JSClass, args: *mut raw::JS::CallArgs) -> bool);
wrap!(raw: pub fn JS_HasInstance(cx: *mut raw::JSContext, obj: HandleObject, v: HandleValue, bp: *mut bool) -> bool);
wrap!(raw: pub fn JS_GetConstructor(cx: *mut raw::JSContext, proto: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewObjectWithGivenProto(cx: *mut raw::JSContext, clasp: *const raw::JSClass, proto: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_DeepFreezeObject(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn JS_FreezeObject(cx: *mut raw::JSContext, obj: HandleObject) -> bool);
wrap!(raw: pub fn JS_GetPrototype(cx: *mut raw::JSContext, obj: HandleObject, result: MutableHandleObject) -> bool);
wrap!(raw: pub fn JS_GetPrototypeIfOrdinary(cx: *mut raw::JSContext, obj: HandleObject, isOrdinary: *mut bool, result: MutableHandleObject) -> bool);
wrap!(raw: pub fn JS_SetPrototype(cx: *mut raw::JSContext, obj: HandleObject, proto: HandleObject) -> bool);
wrap!(raw: pub fn JS_IsExtensible(cx: *mut raw::JSContext, obj: HandleObject, extensible: *mut bool) -> bool);
wrap!(raw: pub fn JS_PreventExtensions(cx: *mut raw::JSContext, obj: HandleObject, result: *mut raw::JS::ObjectOpResult) -> bool);
wrap!(raw: pub fn JS_SetImmutablePrototype(cx: *mut raw::JSContext, obj: HandleObject, succeeded: *mut bool) -> bool);
wrap!(raw: pub fn JS_AssignObject(cx: *mut raw::JSContext, target: HandleObject, src: HandleObject) -> bool);
wrap!(raw: pub fn JS_SetAllNonReservedSlotsToUndefined(obj: HandleObject));
wrap!(raw: pub fn JS_GetFunctionId(cx: *mut raw::JSContext, fun: Handle<*mut raw::JSFunction>, name: MutableHandleString) -> bool);
wrap!(raw: pub fn JS_GetFunctionDisplayId(cx: *mut raw::JSContext, fun: Handle<*mut raw::JSFunction>, name: MutableHandleString) -> bool);
wrap!(raw: pub fn JS_GetFunctionLength(cx: *mut raw::JSContext, fun: HandleFunction, length: *mut u16) -> bool);
wrap!(raw: pub fn JS_GetFunctionScript(cx: *mut raw::JSContext, fun: HandleFunction) -> *mut raw::JSScript);
wrap!(raw: pub fn JS_DecompileScript(cx: *mut raw::JSContext, script: HandleScript) -> *mut raw::JSString);
wrap!(raw: pub fn JS_DecompileFunction(cx: *mut raw::JSContext, fun: Handle<*mut raw::JSFunction>) -> *mut raw::JSString);
wrap!(raw: pub fn JS_IndexToId(cx: *mut raw::JSContext, index: u32, arg1: MutableHandleId) -> bool);
wrap!(raw: pub fn JS_CharsToId(cx: *mut raw::JSContext, chars: raw::JS::TwoByteChars, arg1: MutableHandleId) -> bool);
wrap!(raw: pub fn JS_IsIdentifier(cx: *mut raw::JSContext, str_: HandleString, isIdentifier: *mut bool) -> bool);
wrap!(raw: pub fn JS_FindCompilationScope(cx: *mut raw::JSContext, obj: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NewObjectWithoutMetadata(cx: *mut raw::JSContext, clasp: *const raw::JSClass, proto: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_NondeterministicGetWeakMapKeys(cx: *mut raw::JSContext, obj: HandleObject, ret: MutableHandleObject) -> bool);
wrap!(raw: pub fn JS_NondeterministicGetWeakSetKeys(cx: *mut raw::JSContext, obj: HandleObject, ret: MutableHandleObject) -> bool);
wrap!(raw: pub fn JS_CloneObject(cx: *mut raw::JSContext, obj: HandleObject, proto: HandleObject) -> *mut raw::JSObject);
wrap!(raw: pub fn JS_InitializePropertiesFromCompatibleNativeObject(cx: *mut raw::JSContext, dst: HandleObject, src: HandleObject) -> bool);
wrap!(raw: pub fn JS_CopyOwnPropertiesAndPrivateFields(cx: *mut raw::JSContext, target: HandleObject, obj: HandleObject) -> bool);
wrap!(raw: pub fn JS_WrapPropertyDescriptor(cx: *mut raw::JSContext, desc: MutableHandle<raw::JS::PropertyDescriptor>) -> bool);
wrap!(raw: pub fn JS_DefineFunctionsWithHelp(cx: *mut raw::JSContext, obj: HandleObject, fs: *const raw::JSFunctionSpecWithHelp) -> bool);
