set(WASMTIME_VERSION v41.0.3)
set(WASMTIME_URL https://github.com/bytecodealliance/wasmtime/releases/download/${WASMTIME_VERSION}/wasmtime-${WASMTIME_VERSION}-${HOST_ARCH}-${HOST_OS}.tar.xz)
CPMAddPackage(NAME wasmtime URL ${WASMTIME_URL} DOWNLOAD_ONLY TRUE)
set(WASMTIME_DIR ${CPM_PACKAGE_wasmtime_SOURCE_DIR})
set(WASMTIME ${WASMTIME_DIR}/wasmtime CACHE FILEPATH "Path to wasmtime binary")

# Download the WASI preview1→preview2 adapter needed by `wasm-tools component new`.
set(WASI_ADAPTER_PATH ${CMAKE_CURRENT_SOURCE_DIR}/deps/cpm_cache/wasi_snapshot_preview1.reactor.wasm)
if(NOT EXISTS ${WASI_ADAPTER_PATH})
    set(WASI_ADAPTER_URL https://github.com/bytecodealliance/wasmtime/releases/download/${WASMTIME_VERSION}/wasi_snapshot_preview1.reactor.wasm)
    message(STATUS "Downloading WASI preview1 adapter...")
    file(DOWNLOAD ${WASI_ADAPTER_URL} ${WASI_ADAPTER_PATH} STATUS WASI_ADAPTER_DL_STATUS)
    list(GET WASI_ADAPTER_DL_STATUS 0 WASI_ADAPTER_DL_CODE)
    if(NOT WASI_ADAPTER_DL_CODE EQUAL 0)
        message(FATAL_ERROR "Failed to download WASI adapter: ${WASI_ADAPTER_DL_STATUS}")
    endif()
endif()
set(WASI_ADAPTER ${WASI_ADAPTER_PATH} CACHE FILEPATH "Path to WASI preview1 adapter")
