[workspace.package]
version = "0.0.1"
repository = "https://github.com/bytecodealliance/starlingmonkey"
license = "MPL-2.0"
authors = ["The StarlingMonkey project contributors", "The Servo Project Developers"]
edition = "2024"
rust-version = "1.88.0"
publish = false
keywords = ["javascript", "spidermonkey", "wasm", "runtime"]
categories = ["development-tools", "wasm"]

[workspace]
members = [
    "script",
    "script_bindings",
    "starlingshell",
]
resolver = "2"

[workspace.dependencies]
accountable-refcell = "0.2.2"
app_units = "0.7"
atomic_refcell = "0.1.13"
backtrace = "0.3"
base = { path = "shared/base" }
bindgen = { version = "0.72", default-features = false, features = [
    "runtime",
    "prettyplease",
    "experimental",
] }
bincode = "1"
bitflags = "2.9"
constellation_traits = { path = "shared/constellation" }
content-security-policy = { git = "https://github.com/servo/rust-content-security-policy", branch = "servo-csp", features = ["serde"] }
cookie = { package = "cookie", version = "0.18" }
crossbeam-channel = { path = "starling-crossbeam-channel"}
cssparser = { version = "0.35", features = ["serde"] }
data-url = "0.3"
deny_public_fields = { path = "deny_public_fields" }
devtools_traits = { path = "shared/devtools" }
dom_struct = { path = "dom_struct" }
domobject_derive = { path = "domobject_derive" }
embedder_traits = { path = "shared/embedder" }
encoding_rs = "0.8"
fnv = "1.0"
headers = "0.4"
html5ever = "0.35"
http = "1.3"
hyper-util = { version = "0.1", features = ["http2", "tokio"] }
hyper_serde = { path = "hyper_serde" }
indexmap = { version = "2.10.0", features = ["std"] }
ipc-channel = { path = "starling-ipc-channel" }
itertools = "0.14"
js = { package = "mozjs", git = "https://github.com/servo/mozjs", rev = "bbbbf315e89cf91428f3b652ac68146687737259" }
jstraceable_derive = { path = "jstraceable_derive" }
libc = "1.0.0-alpha.1"
log = "0.4"
mach2 = "0.4"
malloc_size_of = { path = "malloc_size_of" }
malloc_size_of_derive = "0.1"
mime = "0.3.13"
net_traits = { path = "shared/net" }
num-traits = "0.2.19"
parking_lot = "0.12"
percent-encoding = "2.3"
phf = "0.11"
proc-macro2 = "1.0.101"
profile_traits = { path = "shared/profile" }
quote = "1.0.40"
rand = "0.8"
rand_core = "0.6"
rand_isaac = "0.3"
regex = "1.11"
rustc-hash = "2.1.1"
rustls-pki-types = "1.12"
script = { path = "script" }
script_bindings = { path = "script_bindings" }
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_bytes = "0.11"
serde_core = "1.0.226"
serde_json = "1.0"
servo_arc = { git = "https://github.com/servo/stylo", branch = "2025-08-01", features = ["servo"] }
servo_config = { path = "config" }
servo_url = { path = "url" }
smallvec = { version = "1.15", features = ["serde", "union"] }
storage_traits = { path = "shared/storage" }
string_cache = { version = "0.8.9" }
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
stylo_atoms = { git = "https://github.com/servo/stylo", branch = "2025-09-02" }
stylo_config = "0.6.0"
stylo_malloc_size_of = { git = "https://github.com/servo/stylo", branch = "2025-09-02" }
syn = "2.0.106"
synstructure = "0.13.2"
tikv-jemalloc-sys = "0.6.0"
tikv-jemallocator = "0.6.0"
time = { package = "time", version = "0.3", features = ["large-dates", "local-offset", "serde"] }
tracing = "0.1.41"
url = { version = "2.5", features = ["serde"] }
urlpattern = "0.3"
uuid = { version = "1.12.1", features = ["v4"] }
windows-sys = "0.61"

[workspace.lints]

[profile.release]
lto = true
panic = 'abort'

[profile.dev]
panic = 'abort'

[profile.dev.build-override]
opt-level = 3

[profile.release-small]
inherits = "release"
opt-level = "s"
strip = "all"